// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IOracle";
  readonly sourceName: "contracts/interfaces/IOracle.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"marketId","type":"uint256"}],"name":"getResult","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IOracle.sol";
  readonly buildInfoId: "solc-0_8_20-847bf590e2da6db1ae9db8c4e9c0b063e35fe43d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IOracle"]: IOracle$Type;
    ["contracts/interfaces/IOracle.sol:IOracle"]: IOracle$Type;
  }
}